# Development Environment Configuration
# Legal Document Intelligence Platform

environment: development
debug: true
log_level: DEBUG

# BigQuery Configuration
bigquery:
  project_id: "faizal-hackathon"
  location: "US"
  dataset_prefix: "dev_"

# AI Models Configuration
ai_models:
  legal_extractor:
    model_type: "GEMINI_PRO"
    max_tokens: 2048
  legal_summarizer:
    model_type: "GEMINI_PRO"
    max_tokens: 1024
  urgency_detector:
    model_type: "GEMINI_PRO"
    max_tokens: 512

# Data Processing
data_processing:
  batch_size: 10
  max_retries: 3
  timeout_seconds: 300

# API Configuration
api:
  host: "localhost"
  port: 8000
  workers: 1
  reload: true

# Monitoring
monitoring:
  enabled: true
  metrics_interval: 60
  log_retention_days: 7
